### ISSUE TITLE
Discuss: how about migrate `tailwindcss` to `unocss`？

### ISSUE THREAD

**Issue by zouhangwithsweet** [neo-hack/webext-template#13]
Here is some reasons：

- unocss is more flexible, it can use random number gap; lile `px-2.25` `m-.725`
- unocss support `unocss-icon`, it can use many free icons; like `<span classs="i-carbon:checked"></span>`
- unocss doesnot need `postcss`, so we can decrease the `node_modules` volume and get more efficient hmr

**Comment by JiangWeixian** [comment]
Sorry, I not familiar with unocss. I think it's easy to replace tailwindcss with unocss, just like https://github.com/xlzy520/vitesse-webext/tree/refactor/mv3

**Comment by zouhangwithsweet** [comment]
of course, thanks :)
